model:
  name: convnext_base
  img_size: 416
  dropout: 0.30

data:
  images_dir_train: train_images
  images_dir_val: val_images
  images_dir_test: test_images
  train_csv: data/train_data.csv
  val_csv: data/val_data.csv
  test_csv: data/test_data.csv
  file_col: new_filename
  label_cols: [normal, bacteria, virus, COVID-19]
  num_classes: 4

train:
  seed: 3003
  epochs: 40
  batch_size: 8
  num_workers: 8
  lr: 0.00008
  weight_decay: 0.0004
  optimizer: adamw
  loss: improved_focal
  focal_alpha: [1.0, 1.0, 1.8, 18.0]
  focal_gamma: 2.8
  label_smoothing: 0.08
  use_mixup: true
  mixup_prob: 0.5
  use_cutmix: true
  cutmix_prob: 0.4
  use_swa: true
  swa_start: 30
  swa_lr: 0.00002
  use_ema: true
  ema_decay: 0.9999
  early_stopping_patience: 12
  scheduler: cosine
  warmup_epochs: 3
  augment: true
  advanced_aug: true
  use_weighted_sampler: true

out:
  dir: outputs/diverse_model1
  checkpoint_path: outputs/diverse_model1/best.pt
  submission_path: data/submission_diverse1.csv
