model:
  name: efficientnet_v2_s
  img_size: 320
  dropout: 0.25

data:
  images_dir_train: train_images
  images_dir_val: val_images
  images_dir_test: test_images
  train_csv: data/train_data.csv
  val_csv: data/val_data.csv
  test_csv: data/test_data.csv
  file_col: new_filename
  label_cols: [normal, bacteria, virus, COVID-19]
  num_classes: 4

train:
  seed: 5005
  epochs: 35
  batch_size: 48
  num_workers: 8
  lr: 0.0001
  weight_decay: 0.0003
  optimizer: adamw
  loss: improved_focal
  focal_alpha: [1.0, 1.0, 1.5, 15.0]
  focal_gamma: 3.0
  label_smoothing: 0.10
  use_mixup: true
  mixup_prob: 0.5
  use_cutmix: true
  cutmix_prob: 0.4
  use_swa: true
  swa_start: 28
  swa_lr: 0.00003
  use_ema: true
  ema_decay: 0.9997
  early_stopping_patience: 12
  scheduler: cosine
  warmup_epochs: 3
  augment: true
  advanced_aug: true
  use_weighted_sampler: true

out:
  dir: outputs/diverse_model3
  checkpoint_path: outputs/diverse_model3/best.pt
  submission_path: data/submission_diverse3.csv
